/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import helper.database;
import helper.reset;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author afgha
 */
public class DataPembayaran extends javax.swing.JFrame {
    reset reset = new reset();
    database db = new database();
    private Connection conn = new helper.database().connect();
    String table = "pembayaran";
    private DefaultTableModel tabmode;
    private final String[] columns = {"id_pelanggan", "jumlah_bayar", "kembalian"};
    /**
     * Creates new form DataPembayaran
     */
    public DataPembayaran() {
        initComponents();
        datatable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    void reset(){
        reset.resetTextFields(this.getContentPane());
        buttonGroup1.clearSelection();
        tAlamat.setText("");
    }
    
    void datatable(){
    Object[] baris = {"id_pembayaran","id_pelanggan" ,"nama", "alamat", "telepon", "email", "jenis_kelamin", "tanggal_lahir", "jumlah_bayar", "kembalian"};
    tabmode = new DefaultTableModel(null, baris);
    tabPembayaran.setModel(tabmode);

    String sql = "SELECT pembayaran.id_pembayaran,pelanggan.id_pelanggan, pelanggan.nama_pelanggan, pelanggan.alamat, pelanggan.telepon, pelanggan.email, pelanggan.jenis_kelamin, pelanggan.tanggal_lahir, pembayaran.jumlah_bayar, pembayaran.kembalian " +
                 "FROM pembayaran INNER JOIN pelanggan ON pembayaran.id_pelanggan = pelanggan.id_pelanggan";

    try {
        Statement stat = conn.createStatement();
        ResultSet res = stat.executeQuery(sql);
        while (res.next()) {
            int idPembayaran = res.getInt("id_pembayaran");
            int idPelanggan = res.getInt("id_pelanggan");
            String namaPelanggan = res.getString("nama_pelanggan");
            String alamatPelanggan = res.getString("alamat");
            String teleponPelanggan = res.getString("telepon");
            String emailPelanggan = res.getString("email");
            String jenisKelamin = res.getString("jenis_kelamin");
            java.sql.Date tanggalLahir = res.getDate("tanggal_lahir");
            int jumlahBayar = res.getInt("jumlah_bayar");
            int kembalian = res.getInt("kembalian");

            String[] data = {String.valueOf(idPembayaran),String.valueOf(idPelanggan), namaPelanggan, alamatPelanggan, teleponPelanggan, emailPelanggan, jenisKelamin, tanggalLahir.toString(), String.valueOf(jumlahBayar), String.valueOf(kembalian)};
            tabmode.addRow(data);
        }
    } catch (SQLException ex) {
        System.out.println("Error: " + ex);
    }



    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabPembayaran = new javax.swing.JTable();
        bSave = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        tIdPembayaran = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tNamaPelanggan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tTelepon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tIdPelanggan = new javax.swing.JTextField();
        bCariPelanggan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAlamat = new javax.swing.JTextArea();
        rbPerempuan = new javax.swing.JRadioButton();
        rbLakiLaki = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        tTanggalLahir = new com.toedter.calendar.JDateChooser();
        tJumlahBayar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tKembalian = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        bCetakNota = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Data Pembayaran");

        tabPembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPembayaranMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabPembayaran);

        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        bEdit.setText("Edit");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        bDelete.setText("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        bCancel.setText("Cancel");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Pembayaran");

        jLabel3.setText("Nama Pelanggan");

        tNamaPelanggan.setEnabled(false);

        jLabel4.setText("Alamat");

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Email");

        tEmail.setEnabled(false);

        jLabel7.setText("No Telepon");

        tTelepon.setEnabled(false);
        tTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTeleponActionPerformed(evt);
            }
        });

        jLabel8.setText("ID Pelanggan");

        bCariPelanggan.setText("Cari");
        bCariPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariPelangganActionPerformed(evt);
            }
        });

        tAlamat.setColumns(20);
        tAlamat.setRows(5);
        tAlamat.setEnabled(false);
        jScrollPane1.setViewportView(tAlamat);

        buttonGroup1.add(rbPerempuan);
        rbPerempuan.setText("Perempuan");
        rbPerempuan.setEnabled(false);

        buttonGroup1.add(rbLakiLaki);
        rbLakiLaki.setText("Laki-Laki");
        rbLakiLaki.setEnabled(false);
        rbLakiLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiLakiActionPerformed(evt);
            }
        });

        jLabel9.setText("Tanggal Lahir");

        tTanggalLahir.setEnabled(false);

        jLabel10.setText("Jumlah Bayar");

        jLabel11.setText("Kembalian");

        bCetakNota.setText("Cetak Nota");
        bCetakNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCetakNotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(387, 387, 387))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tIdPembayaran)
                                            .addComponent(tIdPelanggan)
                                            .addComponent(tNamaPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bCariPelanggan))
                                    .addComponent(tTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rbPerempuan)
                            .addComponent(tTanggalLahir, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(rbLakiLaki)
                            .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tJumlahBayar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tKembalian))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCetakNota)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCancel))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bSave)
                            .addComponent(bEdit)
                            .addComponent(bDelete)
                            .addComponent(bCancel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tIdPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bCariPelanggan))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel4)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(rbLakiLaki)
                                .addGap(18, 18, 18)
                                .addComponent(rbPerempuan)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(tTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCetakNota)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tJumlahBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPembayaranMouseClicked
        int selectedRowIndex = tabPembayaran.getSelectedRow();
        if (selectedRowIndex >= 0) {
            String idPembayaran = tabmode.getValueAt(selectedRowIndex, 0).toString();
            String idPelanggan = tabmode.getValueAt(selectedRowIndex, 1).toString();
            String namaPelanggan = tabmode.getValueAt(selectedRowIndex, 2).toString();
            String alamatPelanggan = tabmode.getValueAt(selectedRowIndex, 3).toString();
            String teleponPelanggan = tabmode.getValueAt(selectedRowIndex, 4).toString();
            String emailPelanggan = tabmode.getValueAt(selectedRowIndex, 5).toString();
            String jenisKelamin = tabmode.getValueAt(selectedRowIndex, 6).toString();
            String tanggalLahir = tabmode.getValueAt(selectedRowIndex, 7).toString();
            String jumlahBayar = tabmode.getValueAt(selectedRowIndex, 8).toString();
            String kembalian = tabmode.getValueAt(selectedRowIndex, 9).toString();

            // Set nilai ke komponen sesuai dengan data yang dipilih
            tIdPembayaran.setText(idPembayaran);
            tIdPelanggan.setText(idPelanggan);
            tNamaPelanggan.setText(namaPelanggan);
            tAlamat.setText(alamatPelanggan);
            tTelepon.setText(teleponPelanggan);
            tEmail.setText(emailPelanggan);

            if (jenisKelamin.equals("Laki-laki")) {
                rbLakiLaki.setSelected(true);
                rbPerempuan.setSelected(false);
            } else if (jenisKelamin.equals("Perempuan")) {
                rbLakiLaki.setSelected(false);
                rbPerempuan.setSelected(true);
            }
            
            tTanggalLahir.setDate(java.sql.Date.valueOf(tanggalLahir));

            tJumlahBayar.setText(jumlahBayar);
            tKembalian.setText(kembalian);
        }
    }//GEN-LAST:event_tabPembayaranMouseClicked

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
       // Validasi form
        if (!isFormValid()) {
            return; // Menghentikan proses penyisipan data ke tabel pembayaran karena form tidak valid
        }

        int idPelanggan = Integer.parseInt(tIdPelanggan.getText());
        int jumlahBayar = Integer.parseInt(tJumlahBayar.getText());
        int kembalian = Integer.parseInt(tKembalian.getText());

        Object[] values = {idPelanggan, jumlahBayar, kembalian};
        try {
            db.insertData(conn, "pembayaran", columns, values);
            datatable();
            resetForm();
//            JOptionPane.showMessageDialog(this, "Data pembayaran berhasil disimpan.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(DataPembayaran.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan data pembayaran.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bSaveActionPerformed
    private boolean isFormValid() {
        // Validasi apakah semua field sudah terisi
        if (tIdPelanggan.getText().isEmpty() || tJumlahBayar.getText().isEmpty() || tKembalian.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Validasi apakah nilai jumlahBayar dan kembalian merupakan angka positif
        try {
            int jumlahBayar = Integer.parseInt(tJumlahBayar.getText());
            int kembalian = Integer.parseInt(tKembalian.getText());

            if (jumlahBayar <= 0 || kembalian < 0) {
                JOptionPane.showMessageDialog(this, "Nilai Jumlah Bayar harus lebih dari 0, dan Kembalian tidak boleh negatif.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Kolom Jumlah Bayar dan Kembalian harus diisi dengan angka.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
   
    }
    private void resetForm() {
        reset.resetTextFields(this.getContentPane());
        buttonGroup1.clearSelection();
        tAlamat.setText("");
    }
    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // Validasi form
        if (!isFormValid()) {
            return; // Menghentikan proses update data pembayaran karena form tidak valid
        }

        int idPembayaran = Integer.parseInt(tIdPembayaran.getText());
        int idPelanggan = Integer.parseInt(tIdPelanggan.getText());
        int jumlahBayar = Integer.parseInt(tJumlahBayar.getText());
        int kembalian = Integer.parseInt(tKembalian.getText());

        Object[] values = {idPelanggan, jumlahBayar, kembalian};
        try {
            String condition = "id_pembayaran = " + idPembayaran;
            db.updateData(conn, "pembayaran", columns, values, condition);
            datatable();
            resetForm();
    //        JOptionPane.showMessageDialog(this, "Data pembayaran berhasil diupdate.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(DataPembayaran.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengupdate data pembayaran.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bEditActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        int selectedRowIndex = tabPembayaran.getSelectedRow();
    if (selectedRowIndex == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data pembayaran yang akan dihapus.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return; // Menghentikan proses jika tidak ada data pembayaran yang dipilih
    }

    int idPembayaran = Integer.parseInt(tabmode.getValueAt(selectedRowIndex, 0).toString());
    int option = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data pembayaran ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (option == JOptionPane.YES_OPTION) {
        try {
            String condition = "id_pembayaran = " + idPembayaran;
            db.deleteData(conn, "pembayaran", condition);
            datatable();
            resetForm();
//            JOptionPane.showMessageDialog(this, "Data pembayaran berhasil dihapus.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(DataPembayaran.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghapus data pembayaran.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        reset();
    }//GEN-LAST:event_bCancelActionPerformed

    private void tTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTeleponActionPerformed

    private void rbLakiLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiLakiActionPerformed

    private void bCariPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariPelangganActionPerformed
       // Validasi apakah kolom ID Pelanggan sudah diisi
        if (tIdPelanggan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kolom ID Pelanggan harus diisi.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int idPelanggan = Integer.parseInt(tIdPelanggan.getText());

        try {
            String sql = "SELECT * FROM pelanggan WHERE id_pelanggan = ?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setInt(1, idPelanggan);
            ResultSet res = stat.executeQuery();

            if (res.next()) {
                tNamaPelanggan.setText(res.getString("nama_pelanggan"));
                tAlamat.setText(res.getString("alamat"));
                tTelepon.setText(res.getString("telepon"));
                tEmail.setText(res.getString("email"));

                String jenisKelamin = res.getString("jenis_kelamin");
                if (jenisKelamin.equalsIgnoreCase("Laki-laki")) {
                    rbLakiLaki.setSelected(true);
                    rbPerempuan.setSelected(false);
                } else if (jenisKelamin.equalsIgnoreCase("Perempuan")) {
                    rbLakiLaki.setSelected(false);
                    rbPerempuan.setSelected(true);
                }

                tTanggalLahir.setDate(res.getDate("tanggal_lahir"));
            } else {
                JOptionPane.showMessageDialog(this, "ID Pelanggan tidak ditemukan.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                // Reset nilai pada form
                tNamaPelanggan.setText("");
                tAlamat.setText("");
                tTelepon.setText("");
                tEmail.setText("");
                rbLakiLaki.setSelected(false);
                rbPerempuan.setSelected(false);
                tTanggalLahir.setDate(null);
                tJumlahBayar.setText("");
                tKembalian.setText("");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mencari data pelanggan.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(DataPembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bCariPelangganActionPerformed

    private void bCetakNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCetakNotaActionPerformed
        String tIdPembayaran  =  this.tIdPembayaran.getText();
        String path =".\\src\\laporan\\buktipembayaran.jasper";
        JasperReport reports; 
        Map<String, Object> parameters = new HashMap<>();
        parameters.put("id_pembayaran", tIdPembayaran);
        try {
            reports = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path, parameters,conn);
            JasperViewer jviewer = new JasperViewer(jprint,false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(DataPembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bCetakNotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bCariPelanggan;
    private javax.swing.JButton bCetakNota;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbLakiLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextArea tAlamat;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tIdPelanggan;
    private javax.swing.JTextField tIdPembayaran;
    private javax.swing.JTextField tJumlahBayar;
    private javax.swing.JTextField tKembalian;
    private javax.swing.JTextField tNamaPelanggan;
    private com.toedter.calendar.JDateChooser tTanggalLahir;
    private javax.swing.JTextField tTelepon;
    private javax.swing.JTable tabPembayaran;
    // End of variables declaration//GEN-END:variables
}
