/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import helper.database;
import helper.reset;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.text.NumberFormat;
import java.text.ParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author afgha
 */
public class dataPemasaran extends javax.swing.JFrame {
    reset reset = new reset();
    database db = new database();
    private Connection conn = new helper.database().connect();
    String table = "pemasaran";
    private DefaultTableModel tabmode;
    String condition = "id_mitra_kerja = ";
    String[] columns = {"id_mitra_kerja", "jenis_layanan", "nama_brand","periode", "tanggal","barang_masuk","barang_keluar","stok_tersisa","analisa_pasar"};
    /**
     * Creates new form dataPemasaran
     */
    public dataPemasaran() {
        initComponents();
        datatable();
    }
    
    void datatable(){
        Object[] baris = {"id_mitra_kerja", "jenis_layanan", "nama_brand", "periode", "tanggal", "barang_masuk", "barang_keluar", "stok_tersisa", "analisa_pasar"};
        tabmode = new DefaultTableModel(null, baris);
        tabPemasaran.setModel(tabmode);
        String sql = "SELECT * FROM pemasaran"; // Sesuaikan dengan nama tabel pemasaran di database Anda
        try {
            Statement stat = conn.createStatement();
            ResultSet res = stat.executeQuery(sql);
            while (res.next()) {
                String idMitraKerja = res.getString("id_mitra_kerja");
                String jenisLayanan = res.getString("jenis_layanan");
                String namaBrand = res.getString("nama_brand");
                String periode = res.getString("periode");
                String tanggal = res.getString("tanggal");
                String barangMasuk = res.getString("barang_masuk");
                String barangKeluar = res.getString("barang_keluar");
                String stokTersisa = res.getString("stok_tersisa");
                String analisaPasar = res.getString("analisa_pasar");
                String[] data = {idMitraKerja, jenisLayanan, namaBrand, periode, tanggal, barangMasuk, barangKeluar, stokTersisa, analisaPasar};
                tabmode.addRow(data);
            }
        } catch (SQLException ex) {
            System.out.println("Error: " + ex);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabPemasaran = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tIdMitra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tJenisLayanan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tNamaBrand = new javax.swing.JTextField();
        tPeriode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tBarangMasuk = new javax.swing.JTextField();
        tBarangKeluar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tTanggal = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAnalisaPasar = new javax.swing.JTextArea();
        bSave = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tStokTersisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Data Pemasaran");

        tabPemasaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabPemasaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPemasaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabPemasaran);

        jLabel2.setText("ID Mitra Kerja");

        jLabel3.setText("Jenis Layanan");

        jLabel4.setText("Nama Brand");

        tNamaBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaBrandActionPerformed(evt);
            }
        });

        jLabel5.setText("Periode");

        jLabel6.setText("Tanggal");

        jLabel7.setText("Barang Masuk");

        jLabel8.setText("Barang Keluar");

        jLabel9.setText("Analisa Pasar");

        tAnalisaPasar.setColumns(20);
        tAnalisaPasar.setRows(5);
        jScrollPane2.setViewportView(tAnalisaPasar);

        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        bEdit.setText("Edit");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        bDelete.setText("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        bCancel.setText("Cancel");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        jLabel10.setText("Stok Tersisa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(27, 27, 27)
                            .addComponent(tIdMitra))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(26, 26, 26)
                            .addComponent(tJenisLayanan))
                        .addComponent(tPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addGap(32, 32, 32))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(23, 23, 23)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10))
                                    .addGap(25, 25, 25)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tNamaBrand)
                                .addComponent(tTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                .addComponent(tBarangMasuk)
                                .addComponent(tBarangKeluar)
                                .addComponent(tStokTersisa))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bCancel)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(439, 439, 439))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tIdMitra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tJenisLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tNamaBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tBarangMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tStokTersisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bEdit)
                            .addComponent(bDelete)
                            .addComponent(bCancel)
                            .addComponent(bSave))))
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabPemasaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPemasaranMouseClicked
        int selectedRowIndex = tabPemasaran.getSelectedRow();
        String a = tabmode.getValueAt(selectedRowIndex, 0).toString();
        String b = tabmode.getValueAt(selectedRowIndex, 1).toString();
        String c = tabmode.getValueAt(selectedRowIndex, 2).toString();
        String d = tabmode.getValueAt(selectedRowIndex, 3).toString();
        String e = tabmode.getValueAt(selectedRowIndex, 4).toString();
        String f = tabmode.getValueAt(selectedRowIndex, 5).toString();
        String g = tabmode.getValueAt(selectedRowIndex, 6).toString();
        String h = tabmode.getValueAt(selectedRowIndex, 7).toString();
        String i = tabmode.getValueAt(selectedRowIndex, 8).toString();

        tIdMitra.setText(a);
        tJenisLayanan.setText(b);
        tNamaBrand.setText(c);
        tPeriode.setText(d);
        tTanggal.setDate(java.sql.Date.valueOf(e)); // Mengubah String tanggal menjadi java.sql.Date
        tBarangMasuk.setText(f);
        tBarangKeluar.setText(g);
        tStokTersisa.setText(h);
        tAnalisaPasar.setText(i);

    }//GEN-LAST:event_tabPemasaranMouseClicked

    private void tNamaBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaBrandActionPerformed
    
    // Fungsi untuk memeriksa apakah semua kolom pada form tidak boleh kosong
private boolean isFormFilled() {
    String idMitra = tIdMitra.getText();
    String jenisLayanan = tJenisLayanan.getText();
    String namaBrand = tNamaBrand.getText();
    String periode = tPeriode.getText();
    java.util.Date utilTanggal = tTanggal.getDate();
    String barangMasukStr = tBarangMasuk.getText();
    String barangKeluarStr = tBarangKeluar.getText();
    String stokTersisaStr = tStokTersisa.getText();
    String analisaPasar = tAnalisaPasar.getText();

    // Cek jika ada kolom yang kosong
    if (idMitra.isEmpty() || jenisLayanan.isEmpty() || namaBrand.isEmpty() || periode.isEmpty() ||
        barangMasukStr.isEmpty() || barangKeluarStr.isEmpty() || stokTersisaStr.isEmpty() || analisaPasar.isEmpty() || utilTanggal == null) {
        JOptionPane.showMessageDialog(this, "Semua kolom harus diisi dengan benar.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    // Cek jika kolom Barang_Masuk, Barang_Keluar, dan Stok_Tersisa mengandung angka
    try {
        int barangMasuk = Integer.parseInt(barangMasukStr);
        int barangKeluar = Integer.parseInt(barangKeluarStr);
        int stokTersisa = Integer.parseInt(stokTersisaStr);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Kolom Barang Masuk, Barang Keluar, dan Stok Tersisa harus diisi dengan angka.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    // Cek apakah idMitra ada di tabel partnership
    try {
        String sql = "SELECT COUNT(*) FROM partnership WHERE id_mitra_kerja = ?";
        PreparedStatement stat = conn.prepareStatement(sql);
        stat.setString(1, idMitra);
        ResultSet res = stat.executeQuery();
        res.next();
        int count = res.getInt(1);
        if (count == 0) {
            JOptionPane.showMessageDialog(this, "ID Mitra tidak ada di table partnership.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    } catch (SQLException ex) {
        Logger.getLogger(dataPemasaran.class.getName()).log(Level.SEVERE, null, ex);
        return false;
    }

    return true;
}
    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        if (!isFormFilled()) {
            return; // Menghentikan proses penyisipan data ke tabel pemasaran karena form tidak valid
        }
        
        String idMitra = tIdMitra.getText();
        String jenisLayanan = tJenisLayanan.getText();
        String namaBrand = tNamaBrand.getText();
        String periode = tPeriode.getText();
        java.sql.Date tanggal = new java.sql.Date(tTanggal.getDate().getTime());
        String barangMasukStr = tBarangMasuk.getText();
        String barangKeluarStr = tBarangKeluar.getText();
        String stokTersisaStr = tStokTersisa.getText();
        String analisaPasar = tAnalisaPasar.getText();


        Object[] values = {idMitra, jenisLayanan, namaBrand, periode, tanggal, barangMasukStr, barangKeluarStr, stokTersisaStr, analisaPasar};
        try {
            db.insertData(conn, "pemasaran", columns, values);
            datatable();
            reset.resetTextFields(this.getContentPane());
            tAnalisaPasar.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(dataPemasaran.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_bSaveActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        if (!isFormFilled()) {
            return; // Menghentikan proses penyisipan data ke tabel pemasaran karena form tidak valid
        }
        String idMitraKerja = tIdMitra.getText();
        String jenisLayanan = tJenisLayanan.getText();
        String namaBrand = tNamaBrand.getText();
        String periode = tPeriode.getText();
        java.sql.Date tanggal = new java.sql.Date(tTanggal.getDate().getTime());
        String barangMasuk = tBarangMasuk.getText();
        String barangKeluar = tBarangKeluar.getText();
        String stokTersisa = tStokTersisa.getText();
        String analisaPasar = tAnalisaPasar.getText();

        try {
            // Kolom yang akan diupdate (kecuali ID_Mitra_Kerja karena itu merupakan primary key)
            String[] columnsUpdate = {"jenis_layanan", "nama_brand", "periode", "tanggal", "barang_masuk", "barang_keluar", "stok_tersisa", "analisa_pasar"};

            // Data baru yang akan diupdate ke dalam database
            Object[] values = {jenisLayanan, namaBrand, periode, tanggal, barangMasuk, barangKeluar, stokTersisa, analisaPasar};

            // Kondisi untuk update data, misalnya berdasarkan ID_Mitra_Kerja
            String condition = "id_mitra_kerja = ";

            db.updateData(conn, table, columnsUpdate, values, condition + idMitraKerja);
            datatable();
            reset.resetTextFields(this.getContentPane());
            tAnalisaPasar.setText("");;
        } catch (SQLException ex) {
            Logger.getLogger(dataPartnership.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bEditActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        String idMitraKerja = tIdMitra.getText();

        // Validasi apakah ID Mitra Kerja tidak kosong
        if (idMitraKerja.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kolom ID Mitra Kerja tidak boleh kosong.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return; // Menghentikan proses penghapusan data dari tabel partnership
        }

        // Konfirmasi penghapusan data
        int confirm = JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                db.deleteData(conn, "pemasaran", condition + idMitraKerja);
                reset.resetTextFields(this.getContentPane());
                tAnalisaPasar.setText("");
                datatable();
            } catch (SQLException ex) {
                Logger.getLogger(dataPemasaran.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        reset.resetTextFields(this.getContentPane());
        tAnalisaPasar.setText("");
    }//GEN-LAST:event_bCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataPemasaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataPemasaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataPemasaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataPemasaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataPemasaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea tAnalisaPasar;
    private javax.swing.JTextField tBarangKeluar;
    private javax.swing.JTextField tBarangMasuk;
    private javax.swing.JTextField tIdMitra;
    private javax.swing.JTextField tJenisLayanan;
    private javax.swing.JTextField tNamaBrand;
    private javax.swing.JTextField tPeriode;
    private javax.swing.JTextField tStokTersisa;
    private com.toedter.calendar.JDateChooser tTanggal;
    private javax.swing.JTable tabPemasaran;
    // End of variables declaration//GEN-END:variables
}
